In [1]:
A = np.matrix([[0.5,-1],[0,3/4]])
B = np.matrix([-2,4])
print ('B.T',B.T.shape)
s = A* B.T
print('s',s)


B.T (2, 1)
s [[-5.]
 [ 3.]]


In [2]:
A = np.matrix([[1,0],[0,8]])
print ('A',A)
B = np.matrix([[1,0],[-0.5,1]])
print ('B',B)

M = A*B
print ('M',M)

A [[1 0]
 [0 8]]
B [[ 1.   0. ]
 [-0.5  1. ]]
M [[ 1.  0.]
 [-4.  8.]]


In [3]:
#Solving linear equations using the inverse matrix

A = np.matrix([[1, 1, 3],
     [1, 2, 4],
     [1, 1, 2]])
Ainv = np.linalg.inv(A)

#Use this code block to solve the following linear system with numpy. Ar=s,
A = [[4, 6, 2],
     [3, 4, 1],
     [2, 8, 13]]

s = [9, 7,2]

r = np.linalg.solve(A, s)
print('r',r)

r [ 3.  -0.5  0. ]


In [4]:
A = np.array([[4, 6, 2],
     [3, 4, 1],
     [2, 8, 13]], dtype=np.float_)

B = np.array([9, 7, 2], dtype=np.float_)

print ('A',A,'B',B)


B[0] = B[0]/ A[0][0]
A[0] = A[0]/ A[0][0]
print ('A',A, 'B[0]',B[0])

B[1] = B[1]-A[1][0]*B[0]
A[1] = A[1]-A[1][0]*A[0]
B[1] = B[1]/A[1][1]
A[1] = A[1]/ A[1][1]

print ('A',A, 'B[1]',B[1])


B[2] = B[2]-A[2][0]*B[0]
A[2] = A[2]-A[2][0]*A[0]
B[2] = B[2]- A[2][1]*B[1]
A[2] = A[2]- A[2][1]*A[1]
B[2] = B[2]/ A[2][2]
A[2] = A[2]/ A[2][2]

print ('A',A, 'B[2]',B[2])

A [[ 4.  6.  2.]
 [ 3.  4.  1.]
 [ 2.  8. 13.]] B [9. 7. 2.]
A [[ 1.   1.5  0.5]
 [ 3.   4.   1. ]
 [ 2.   8.  13. ]] B[0] 2.25
A [[ 1.   1.5  0.5]
 [-0.   1.   1. ]
 [ 2.   8.  13. ]] B[1] -0.5
A [[ 1.   1.5  0.5]
 [-0.   1.   1. ]
 [ 0.   0.   1. ]] B[2] 0.0


# Solving linear equations using the inverse matrix

In [11]:
#You go to the shops on Monday and buy 1 apple, 1 banana, and 1 carrot; 
#the whole transaction totals €15. On Tuesday you buy 3 apples, 2 bananas,
#1 carrot, all for €28. Then on Wednesday 2 apples, 1 banana, 2 carrots, for €23.

A = [[1,1,1],
     [3, 2, 1],
     [2, 1, 2]]

s = [15, 28, 23]

AA = np.matrix([[4,6,2],[3, 4, 1],[2, 8, 13]])

#AA = np.matrix([[1,3/2,1/2],
     #[3, 4, 1],
     #[2, 8, 13]])

ss = [9, 7, 2]

print('AA:\n',AA)
print('ss:\n',ss)


A1 = AA[0,:]/4 
S1 = ss[0]/4 
print('A1:\n',A1)


A2 = (AA[1,:]-3*A1)*-2
S2 = (ss[1]-3*S1)*-2

print('A2:\n',A2)
print('S2:\n',S2)

AA:
 [[ 4  6  2]
 [ 3  4  1]
 [ 2  8 13]]
ss:
 [9, 7, 2]
A1:
 [[1.  1.5 0.5]]
A2:
 [[0. 1. 1.]]
S2:
 -0.5


In [13]:
x = np.linalg.solve(AA, ss)
print('x',x)

x [ 3.  -0.5  0. ]


In practice, for larger systems, one never solves a linear system by hand as there are software packages that can do this for you - such as numpy in Python.

Use this code block to see numpy invert a matrix.

You can try to invert any matrix you like. Try it out on your answers to the previous question.

In [18]:
import numpy as np

A = [[1, 1, 3],
     [1, 2, 4],
     [1, 1, 2]]
Ainv = np.linalg.inv(A)
print ('Ainv',Ainv)

Ainv [[ 0. -1.  2.]
 [-2.  1.  1.]
 [ 1. -0. -1.]]


In general, one shouldn't calculate the inverse of a matrix unless absolutely necessary. It is more computationally efficient to solve the linear algebra system if that is all you need.

Use this code block to solve the following linear system with numpy. Ar=s,

In [19]:
import numpy as np
A = [[4, 6, 2],
     [3, 4, 1],
     [2, 8, 13]]

s = [9, 7, 2]

r = np.linalg.solve(A, s)
print ('r:',r)

r: [ 3.  -0.5  0. ]


# Non-square matrix multiplication


In [33]:
a = np.matrix([2,4,5,6])
print(a.shape)
b = np.matrix([1,3,2,1]).T
c = np.dot(a,b)
print('c',c)

c1 = np.dot(b,a)
print('c',c1)

(1, 4)
c [[30]]
c [[ 2  4  5  6]
 [ 6 12 15 18]
 [ 4  8 10 12]
 [ 2  4  5  6]]


In [39]:
a = np.matrix([[2,-1],[0,3],[1,0]])
print(a.shape)
b = np.matrix([[0,1,4,-1],[-2,0,0,2]])
c = np.dot(a,b)
print('c:',c)

a = np.matrix([[1,0],[0,1]])
print(a.shape)
b = np.matrix([[1,2,3],[4,5,6]])
c = np.dot(a,b)
print('c:',c)

(3, 2)
c: [[ 2  2  8 -4]
 [-6  0  0  6]
 [ 0  1  4 -1]]
(2, 2)
c: [[1 2 3]
 [4 5 6]]
